config/routes.rb
Rails.application.routes.draw do
  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :items
  has_many :model1, through: :model2
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :carts
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout false
  # curl -d "name=Iphone11&price=1100&description=Ok" -X POST http://localhost:5000/items
  skip_before_action :verify_authenticity_token
  before_action :find_item, only: %i[show edit update destroy upvote]
  before_action :admin?, only: %i[edit update new create destroy]
  after_action :show_info, only: %i[index]

  def index
    @items = Item.all
  end

  def create
    item = Item.create(items_params)
    if item.persisted?
      redirect_to items_path
    else
      render body: item.errors, status: :unprocessable_entity
    end
  end

  def new; end

  def show
    render body: "Page not found", status: 404 unless @item
  end

  def edit
    unless(@item)
      render body: "Page not found", status: 404
    end
  end

  def update
    if @item.update(items_params)
      redirect_to item_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
    redirect_to items_path
  end

  def destroy
    if @item.destroy.destroyed?
      redirect_to items_path
    else
      render body: item.errors, status: :unprocessable_entity
    end
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to items_path
  end

  def expensive
    @items = Item.where('price >=  50')
    render :index
  end

  private
  def items_params
    params.permit(:name, :price, :weight, :description)
  end

  def find_item
    @item = Item.find_by(id: params[:id])
  end

  def admin?
    true
    # render json: 'Access denied', status: :forbidden unless params[:admin]
  end

  def show_info
    puts "Somehow after show info"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2 style="color: #B00100; margin: 0 auto">Edit <%= @item.name %></h2>

<%= form_tag items_path(@item), method: :post do %>
<%= label_tag :name %>
<%= text_field_tag :name, @item.name %>
<%= label_tag :price %>
<%= text_field_tag :price, @item.price %>
<%= label_tag :weight %>
<%= text_field_tag :weight, @item.weight %>
<%= label_tag :description %>
<%= text_field_tag :description, @item.description %>
<%= submit_tag "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/index.html.erb
<h2 style="color: #b00100; margin: 0 auto">all items</h2><br />

<table>
  <tr>
    <th>Item Id</th>
    <th>Name</th>
    <th>Weight</th>
    <th>Price</th>
    <th>Description</th>
    <th>Rating</th>
    <th>Remove</th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= link_to item.name, item_path(item) %></td>
    <td><%= item.price %></td>
    <td><%= item.weight %></td>
    <td><%= item.description %></td>
    <td><%= item.votes_count %>, <%= link_to '+', upvote_item_path(item) %></td>
    <td></td>
    <td><%= button_to 'remove', item_path(item), method: :delete %></td>
  </tr>
  <% end %>
</table>
<br />
<%= link_to 'new Item', new_item_path %>
<br>
<%= link_to 'Expensive price', expensive_items_path %>
<br>
<%= link_to 'All items', items_path %>

app/views/items/new.html.erb
<h2 style="color: #B00100; margin: 0 auto">New item</h2>

<%= form_tag items_path, method: :post do %>
<%= label_tag :name %>
<%= text_field_tag :name %>
<%= label_tag :price %>
<%= text_field_tag :price %>
<%= label_tag :description %>
<%= text_field_tag :description %>
<%= label_tag :weight %>
<%= text_field_tag :weight %>
<%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/show.html.erb
<h2 style="color: #b00100; margin: 0 auto">show items</h2><br />

<h4><%= @item.name %></h4>

<ul>
  <li>Price: <%= @item.price %> $ </li>
  <li>Weight: <%= @item.weight %></li>
  <li>Description: <%= @item.description %></li>
</ul>

<%= link_to "edit #{@item.name}" , edit_item_path %>
<br />
<%= link_to 'items', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCource</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>